### ISSUE TITLE
Windows USB device not found

### ISSUE THREAD

**Issue by fommil** [cibuddy/cibuddy#23]
Hi all,

I'm using cibuddy as a dependency in my project, for your binary builds of the java usb backends.

I don't have access to a Windows machine and a user has recently reported the following

  https://github.com/fommil/emokit-java/issues/13

Essentially, I'm not seeing any USB device. Is there some command I can ask them to run, or some config screen, so that I can confirm that their USB device should be accessible from Java?

**Comment by mirkojahn** [comment]
Well, for this I am using JUnit test (which currently disabled to also run on the CI-Servers). Basically copy that class, remove the "Ignore" annotation and run the test.

https://github.com/cibuddy/cibuddy/blob/master/drivers/hid/src/test/java/com/codeminders/hidapi/HIDManagerTest.java

Hope that helps...

**Comment by fommil** [comment]
@mirkojahn thanks for this – I was hoping for a Windows binary (like `lsusb` or something) or system config window to look at (listing all usb devices) so that the user didn't have to build / run any code. This test isn't part of the `jar` is it?

**Comment by fommil** [comment]
(There was a `main` in the original javahidapi that did something like this, I recall)

**Comment by mirkojahn** [comment]
OK, I wrote a short helper to sort out this problem. You basically have to download the hid jar file from the maven repository here (currently, the latest one is called: hid-1.0.1-20130115.205004-2.jar):
https://oss.sonatype.org/content/repositories/snapshots/com/cibuddy/hid/1.0.1-SNAPSHOT/
and the call:

```
java -jar hid-1.0.1-20130115.205004-2.jar
```

My output looked like this on Mac OS X (10.8.2):

```
HID Devices:

0.  HIDDeviceInfo [path=USB_05ac_024d_0x7fdce41106c0, vendor_id=1452, product_id=589, serial_number=, release_number=0, manufacturer_string=Apple Inc., product_string=Apple Internal Keyboard / Trackpad, usage_page=1, usage=2, interface_number=-1]
---------------------------------------------

1.  HIDDeviceInfo [path=USB_05ac_024d_0x7fdce41115e0, vendor_id=1452, product_id=589, serial_number=, release_number=521, manufacturer_string=Apple Inc., product_string=Apple Internal Keyboard / Trackpad, usage_page=65280, usage=1, interface_number=-1]
---------------------------------------------

2.  HIDDeviceInfo [path=USB_05ac_024d_0x7fdce4110f90, vendor_id=1452, product_id=589, serial_number=, release_number=521, manufacturer_string=Apple Inc., product_string=Apple Internal Keyboard / Trackpad, usage_page=1, usage=2, interface_number=-1]
---------------------------------------------

3.  HIDDeviceInfo [path=USB_05ac_024d_0x7fdce4111cb0, vendor_id=1452, product_id=589, serial_number=, release_number=521, manufacturer_string=Apple Inc., product_string=Apple Internal Keyboard / Trackpad, usage_page=1, usage=6, interface_number=-1]
---------------------------------------------

4.  HIDDeviceInfo [path=, vendor_id=0, product_id=0, serial_number=, release_number=0, manufacturer_string=, product_string=Apple Mikey HID Driver, usage_page=12, usage=1, interface_number=-1]
---------------------------------------------
```

And like this on Windows 7 (64-bit):

```
HID Devices:

0.      HIDDeviceInfo [path=\\?\hid#vid_05ac&pid_024f&mi_00#9&342b8256&0&0000#{4
d1e55b2-f16f-11cf-88cb-001111000030}, vendor_id=1452, product_id=591, serial_num
ber=?, release_number=116, manufacturer_string=Apple Inc., product_string=Apple
Keyboard, usage_page=1, usage=6, interface_number=0]
---------------------------------------------

1.      HIDDeviceInfo [path=\\?\hid#vid_05ac&pid_024f&mi_01#9&1c67f611&0&0000#{4
d1e55b2-f16f-11cf-88cb-001111000030}, vendor_id=1452, product_id=591, serial_num
ber=?, release_number=116, manufacturer_string=Apple Inc., product_string=Apple
Keyboard, usage_page=12, usage=1, interface_number=1]
---------------------------------------------

2.      HIDDeviceInfo [path=\\?\hid#vid_1130&pid_0002&mi_00#9&9441c56&0&0000#{4d
1e55b2-f16f-11cf-88cb-001111000030}, vendor_id=4400, product_id=2, serial_number
=?, release_number=256, manufacturer_string=?, product_string=i-Buddy, usage_pag
e=1, usage=0, interface_number=0]
---------------------------------------------

3.      HIDDeviceInfo [path=\\?\hid#vid_1130&pid_0002&mi_01#9&2d1b5a18&0&0000#{4
d1e55b2-f16f-11cf-88cb-001111000030}, vendor_id=4400, product_id=2, serial_numbe
r=?, release_number=256, manufacturer_string=?, product_string=i-Buddy, usage_pa
ge=1, usage=3, interface_number=1]
---------------------------------------------
```

**Comment by susmith** [comment]
@mirkojahn ., 

I have downloaded hid-1.0.1.jar
and proceeded with 
java -jar hid-1.0.1-20130115.205004-2.jar

I got the following output in WINDOWS 7 - (32 bit)
![hid-usb](https://f.cloud.github.com/assets/2708730/71564/082512d4-5fee-11e2-862f-43b52796400a.jpg)

I hope hid-1.0.1.jar updated was identifying USB dongle successful in windows7

**Comment by mirkojahn** [comment]
Actually the 1.0.1-SNAPSHOT jar only additionally contains the Main class for the test. The implementation of the HID handling didn't change between 1.0.0 and 1.0.1-SNAPSHOT. So, the problem most likely is located somewhere in the usage of the API or above. I'm closing this one, because the access und Win7 seems to be ok.
